import cv2

N_FRAMES_FPS_LOG = 30

FRAME_METADATA_H = 20
NODE_FRAME_WIDTH = 105
SYNC_FRAME_WIDTH = 5

NODE_FRAME_BG_ACTIVE = (75, 75, 75)
NODE_FRAME_BG_INACTIVE = 0

NODE_FRAME_FG_ACTIVE = (255, 255, 255)
NODE_FRAME_FG_INACTIVE = (100, 100, 100)
NODE_FRAME_FONT_SIZE = 1.3
NODE_FRAME_STEP_SCROLL = 3
NODE_FRAME_FONT_WEIGHT = 2

FORCE_TIMESTAMPS = True

FRAME_METADATA_BYTE_ID = 1
FRAME_METADATA_BYTE_LABEL = 6
FRAME_METADATA_BYTE_DATA = 8
FRAME_METADATA_BYTE = FRAME_METADATA_BYTE_ID + FRAME_METADATA_BYTE_LABEL + FRAME_METADATA_BYTE_DATA

VIDEO_CONTAINER = '.avi'
VIDEO_CODEC = 'MP42'

FONT = cv2.FONT_HERSHEY_PLAIN

PLAYBACK_SPEEDUP = 1.06

ALLOW_DUMMY_PROCESSING = False

METADATA_LINE_TYPE = cv2.LINE_AA
